### ISSUE TITLE
Node Issues

### ISSUE THREAD

**Issue by JuicePlum6** [pierre-josselin/payday-2-ultimate-trainer-6#1]
So. i installed node and others etc followed the youtube tutorial and this happens 
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/89342718/ad018666-dec2-4a95-afed-e13b193bba8f)
any fixes?

**Comment by pierre-josselin** [comment]
If yes, please confirm the install folder of your node (probably C:\Program Files\nodejs) and i will give you a possible solution

**Comment by pierre-josselin** [comment]
I close this issue since there is no updates.
Open a new issue if you need more help!
