### ISSUE TITLE
Issue While installing the trainer

### ISSUE THREAD

**Issue by MicahPanda** [pierre-josselin/payday-2-ultimate-trainer-6#101]
Whenever I run the install shortcut I get this error, I have followed all steps:
![image_2023-11-26_011606969](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/55553764/57619f64-f2ad-44d4-b79b-efdbab54bc39)

**Comment by pierre-josselin** [comment]
Hi, you can find already installed versions here:
https://drive.google.com/drive/folders/1ii6VwSu2ezoerXJ5Ql59apOgWLU-EIR6?usp=drive_link

**Comment by MicahPanda** [comment]
> Hi, you can find already installed versions here: https://drive.google.com/drive/folders/1ii6VwSu2ezoerXJ5Ql59apOgWLU-EIR6?usp=drive_link

Thank you very much!
