### ISSUE TITLE
Cannot lock achievements?

### ISSUE THREAD

**Issue by tankyap** [pierre-josselin/payday-2-ultimate-trainer-6#107]
It probably just me but is the lock achievement feature is working as usual? I didn't see the "Sent" at the bottom left, and yes other features seems to be working also. I lock an achievement, but the achievement still show it unlocked, am I missing something else?

**Comment by pierre-josselin** [comment]
Hi, If you try to lock/unlock all achievements, it could crash your game/steam, but it should work, if not I invite you to try again in a browser like chrome/firefox instead of Steam.

**Comment by tankyap** [comment]
@pierre-josselin Yeah, it didn't crash my gane tho. Maybe it's because I'm on Epic Games? And yes, the unlocker works like a charm but lock doesn't

**Comment by pierre-josselin** [comment]
Ah yes, [the function](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/blob/main/payday-2-ultimate-trainer-6-mod/classes/UT.lua#L559) we use to lock achievements references to Steam, it may not work properly with Epic.

I can't see Epic specific function to lock an achievement [on the game source code](https://github.com/steam-test1/Payday-2-LuaJIT-Complete/blob/master/lib/managers/achievmentmanager.lua#L850), I think it's not possible on Epic unfortunately
