### ISSUE TITLE
node is not recognized

### ISSUE THREAD

**Issue by demonicboycze** [pierre-josselin/payday-2-ultimate-trainer-6#11]
Hi i have issue with this - when i put folder into mods folder and when i open the folder payday-2-ultimate-trainer-6-main and then install command it says this ------- 'node' is not recognized as an internal or external command,
operable program or batch file. and when i put command : node .\index.js install  from the same directory it still says this ------ 'node' is not recognized as an internal or external command,
operable program or batch file.

**Comment by pierre-josselin** [comment]
Hi, you probably missed this required step:

![Screenshot_20230804-170531-274.png](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/70814177/a6e09b0d-a197-41c0-a9a4-504e6ed028e3)

**Comment by pierre-josselin** [comment]
Closing this issue because no reply.

FYI: 6.2.0 has been released with a troubleshooting section and a debugging tool for people having problems with the installation.
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6#troubleshooting
