### ISSUE TITLE
Mod menu is detected

### ISSUE THREAD

**Issue by Elenimotoon** [pierre-josselin/payday-2-ultimate-trainer-6#110]

**Comment by pierre-josselin** [comment]
Hi, thank you for your message. Yes, some features provided by this mod are detected by the PAYDAY 2 anti-cheat. These features are indicated by a yellow "exclamation mark" symbol. Unfortunately it is not possible to make these features undetectable. Please also note that skins and dlc unlcokers (not included) are detected by the anti cheat. If you don't use all of this you shouldn't be detected by the anti cheat. Please also note that the PAYDAY 2 anti-cheat simply kick the cheater from the lobby, without any other consequences.
