### ISSUE TITLE
[Suggestion] No auto-kick

### ISSUE THREAD

**Issue by Elenimotoon** [pierre-josselin/payday-2-ultimate-trainer-6#111]
It would be great add an no auto kick option from server when equipped a non bought DLC ,but yes allowed the host kicks you for example

**Comment by pierre-josselin** [comment]
Unfortunately it is not possible to prevent the host from kicking someone. However, for the case you describe here (non bought dlc) you can use this: [Full equipment spoofer - no cheater tag](https://www.unknowncheats.me/forum/payday-2-a/424798-equipment-spoofer-cheater-tag.html).
