### ISSUE TITLE
Bug when trying to install the mod

### ISSUE THREAD

**Issue by lukasd2010** [pierre-josselin/payday-2-ultimate-trainer-6#112]
when i try to install it i just get an error in the console that says
An error has occurred:

spawn C:\Windows\system32\cmd.exe;C:\Program Files\Java\jdk-20\bin ENOENT

**Comment by pierre-josselin** [comment]
For information to others, this has been fixed on Discord by running from the ultimate trainer folder, in two different consoles, the following commands:

```
node "node_modules\http-server\bin\http-server" --port 1140 --proxy "http://127.0.0.1:1140?" "payday-2-ultimate-trainer-6-app\dist"
```

```
node "payday-2-ultimate-trainer-6-server\src\index.js"
```
