### ISSUE TITLE
error 102

### ISSUE THREAD

**Issue by Dumanddd** [pierre-josselin/payday-2-ultimate-trainer-6#113]
when i press the ultimate trainer button error 102 pops up and it says im not connected to the interenet even though im

**Comment by pierre-josselin** [comment]
Hi, this should fix your issue:

> ℹ️ For some (Windows 11?) users, the server does not start automatically. If when you launch the game, no console opens, create an empty text file named developer, inside the mods folder.

If still getting the error, please follow this section:

https://github.com/pierre-josselin/payday-2-ultimate-trainer-6?tab=readme-ov-file#troubleshooting
