### ISSUE TITLE
Launching Shayu: Mountain Master Heist crashes the game

### ISSUE THREAD

**Issue by electricguitarr** [pierre-josselin/payday-2-ultimate-trainer-6#116]
i wanted to play the DLC's cause i took a big break and wanted to play the Shayu: Mountain Master Heist but it crashes my game upon loading

**Comment by pierre-josselin** [comment]
Hi, if your game crashes upon loading it may be because there are too many vehicles loaded in the driving menu. Try to unselect all vehicles and restart the game.
