### ISSUE TITLE
Cannot Find Module

### ISSUE THREAD

**Issue by DorkDemon** [pierre-josselin/payday-2-ultimate-trainer-6#117]
I clicked and ran the install file and get this error, any and all help would be appreciated. :

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- D:\SteamLibrary\steamapps\common\PAYDAY 2\mods\payday-2-ultimate-trainer-6-main\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (D:\SteamLibrary\steamapps\common\PAYDAY 2\mods\payday-2-ultimate-trainer-6-main\index.js:2:12)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'D:\\SteamLibrary\\steamapps\\common\\PAYDAY 2\\mods\\payday-2-ultimate-trainer-6-main\\index.js'←[39m
  ]
}

D:\SteamLibrary\steamapps\common\PAYDAY 2\mods\payday-2-ultimate-trainer-6-main>

**Comment by pierre-josselin** [comment]
Hi, it looks like there is an issue with your Node.js installation. I invite you to uninstall it and try to install a different version. You can also try to use the [already installed version of ultimate trainer](https://drive.google.com/drive/folders/1ii6VwSu2ezoerXJ5Ql59apOgWLU-EIR6?usp=drive_link), but I don't think it will fix the issue since it seems to be related to Node.js.

**Comment by DorkDemon** [comment]
ah i see thank you
