### ISSUE TITLE
Spawning bags crashes game instantly

### ISSUE THREAD

**Issue by Atom-mp4** [pierre-josselin/payday-2-ultimate-trainer-6#119]

**Comment by Atom-mp4** [comment]
misclick

**Comment by pierre-josselin** [comment]
Hi, client-side bag spawning is not supported in this mod since the anti cheat is enabled for almost all lobbies. In fact, the option should not be available as a client.

**Comment by pierre-josselin** [comment]
To find you crash file, type this in your windows address bar:

```
%localappdata%\PAYDAY 2
```

**Comment by Atom-mp4** [comment]
> Hi, client-side bag spawning is not supported in this mod since the anti cheat is enabled for almost all lobbies. In fact, the option should not be available as a client.

Alright, Thank you

**Comment by pierre-josselin** [comment]
> To find you crash file, type this in your windows address bar:
> 
> ```
> %localappdata%\PAYDAY 2
> ```

Alternatively, you can found it from the ultimate trainer app, bug icon button at the top right of the screen.
