### ISSUE TITLE
Force Close When Clicking On Payday Ultimate Trainer 6

### ISSUE THREAD

**Issue by vivixizz** [pierre-josselin/payday-2-ultimate-trainer-6#122]
my payday 2 always force closed when i click on the ultimate trainer button at the game main menu I've already followed all the instruction to download the trainer , is there any solution?

**Comment by pierre-josselin** [comment]
Hi, can you share the content of your crashlog please?

C:\Users\%LOCALAPPDATA%\PAYDAY 2

**Comment by vivixizz** [comment]
Application has crashed: C++ exception
...er-6-main/payday-2-ultimate-trainer-6-mod/classes/UT.lua:142: attempt to call method 'overlay_activate' (a nil value)



SCRIPT STACK

callback() @mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-mod/classes/Hook.lua:30
trigger() core/lib/managers/menu/items/coremenuitem.lua:150
core/lib/managers/menu/coremenulogic.lua:286
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
update() lib/setups/setup.lua:863
original() lib/setups/menusetup.lua:354
update() @mods/base/req/core/Hooks.lua:260
core/lib/setups/coresetup.lua:557


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

Hi,this is the crashlog when i click the trainer button in the menu

**Comment by pierre-josselin** [comment]
Hi, the overlay cannot be open, I guess you are not playing on Steam, you can access the app from any web browser like Chrome on the computer running PAYDAY 2, on the following URL:

http://localhost:1140

Just use ALT+TAB to switch to the game/app.
