### ISSUE TITLE
Spam in logs

### ISSUE THREAD

**Issue by Fl414r** [pierre-josselin/payday-2-ultimate-trainer-6#123]
[2024_10_13_log.txt](https://github.com/user-attachments/files/17357169/2024_10_13_log.txt)
21.5mb log with 24h limit, is there anything else to say?

**Comment by pierre-josselin** [comment]
We are continually using the dohttpreq() method provided by SuperBLT to communicate with the local server. This method logs every request and unfortunately we can't do anything about it.
