### ISSUE TITLE
No weapons skin unlock

### ISSUE THREAD

**Issue by esteban142536** [pierre-josselin/payday-2-ultimate-trainer-6#15]
The Ultimate Trainer 5 have an option where you can unlock weapons skins, even if you don't have the DLC, but I cannot find this option

Are you planning to add in the future?

**Comment by thejuves** [comment]
He changed the design of the trainer. The main functions of the application are separate, and DLC Unlocker is now a standalone mod

**Comment by chromKa** [comment]
new DLC unlocker - no unlocked weapon skins. =\
@pierre-josselin Can you fix it? and may you can add this unlocker to UT6? Its better, without standalone version

**Comment by pierre-josselin** [comment]
Hi all,

As @thejuves said, for this new version I have chosen to remove from Ultimate Trainer everything that may represent a financial loss to the game developers. This is why the DLC and Skin unlockers will no longer be included in this mod.

However you can find a standalone version of the DLC unlocker on UnknownCheats.

Feel free to create a reply on the thread in question to request skin unlocking, I could propose an update.

**Comment by chromKa** [comment]
> 

Unlocked DLC and content are also financial losses for developers. But they are available. The situation is twofold.

**Comment by pierre-josselin** [comment]
@chromKa You're right, the idea is just to stop associating Ultimate Trainer with something bad for the game. Users who really need it will always find an alternative (alternative provided on UC).

**Comment by esteban142536** [comment]
@pierre-josselin 
How about create an alternative version, like a complement or plugin to this version ?
Because some DLC unlocked all including DLC's and that result in the Cheating tag
Just to unlock weapons skins and that's it (The ultimate trainer 5 can unlock the skins without the tag)
