### ISSUE TITLE
New locale strings

### ISSUE THREAD

**Issue by chromKa** [pierre-josselin/payday-2-ultimate-trainer-6#18]
@pierre-josselin please, if you add new strings in english locale file - add this english strings to all another locales.
Now english locale mismatch with russian.

**Comment by pierre-josselin** [comment]
Hi,

I confirm that every time I add an entry to the English locale, I also add it at thend of all the other locales.

I think the confusion is that there are two branches [6.2.0](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/tree/6.2.0) (dev unreleased version) and [main](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6) (current version).

You can check here that the russian locale is correctly synchronized with the english locale:

[payday-2-ultimate-trainer-6-app/src/locales/en/main.json](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/blob/6.2.0/payday-2-ultimate-trainer-6-app/src/locales/en/main.json)
[payday-2-ultimate-trainer-6-app/src/locales/ru/main.json](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/blob/6.2.0/payday-2-ultimate-trainer-6-app/src/locales/ru/main.json)

**Comment by pierre-josselin** [comment]
@chromKa is ok for you ? I can close this issue now ?

**Comment by pierre-josselin** [comment]
Closing this issue because no reply.
