### ISSUE TITLE
Gameplay broke after a while

### ISSUE THREAD

**Issue by esteban142536** [pierre-josselin/payday-2-ultimate-trainer-6#19]
I used Ultimate trainer 5, for some reason when I use this version I cannot interact with nothing, that mean no revive, the interaction key just doesn't work at all and all the enemies ignore me, and they don't shoot me, if I grab a bag I cannot throw it

If I change and use the Ultimate trainer 5 everything work without problems, I have tried verifying files and re-install the game, but the error continue

**Comment by pierre-josselin** [comment]
Hi, can you please provide:

- A screenshot of your mods folder
- The contents of the `settings.json` file located in `payday-2-ultimate-trainer-6-main`

**Comment by esteban142536** [comment]
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/72285824/17bf5fea-e028-4bab-bf93-533530b05981)


Setting.json:
`{}`

Be aware that 'UltimateTrainer5' and 'crime.net performance improvement' are disable in the mod manager, already tested my deleting 'UltimateTrainer5'
For some reason, i also cannot join to online games with other players, when i try to join just appear my name without the "Ready" or "Not ready", after wait for a while, other players appear disconected and i cannot join to the game 
![Untitled](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/72285824/86f94a9a-fe49-4e44-a51e-0f6cf966ce38)

**Comment by pierre-josselin** [comment]
Hi,

Thank you for your reply.

Most likely one of the mods you are using is conflicting with UT6. UT6 alone cannot create the problems you describe. Could you try removing all mods to confirm this fixes the problem, then re-add them one at a time to see which one is causing the problem?

**Comment by chromKa** [comment]
maybe need delete UT5, because you are install UT6?

**Comment by esteban142536** [comment]
Update:
For some reason, the connections and gameplay errors happen because of superBLT, if I delete it, the game play how it should
My theory is that is some conflict with the Microsoft Visual c++, that I have multiple version
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/72285824/53c87300-885a-45ea-9841-7c8650855268)

**Comment by pierre-josselin** [comment]
Did you test by removing all of your other mods?

**Comment by pierre-josselin** [comment]
Closed as no updates. Feel free to open a new issue if needed.
