### ISSUE TITLE
Problems with Overlay

### ISSUE THREAD

**Issue by chromKa** [pierre-josselin/payday-2-ultimate-trainer-6#22]
2 times I ran into the problem of opening the overlay after clicking the ULTIMATE TRAINER button in the main menu. The 1st time I was written that I should turn on the overlay (although I did not turn it off). The 2nd time after clicking on this button - nothing happened. The overlay does not start. I noticed that before this 2nd time I clicked on the launch of the game from Steam and the game refused to launch (like a crash), the second time it started, but without an overlay.

**Comment by pierre-josselin** [comment]
Note: I encountered this issue while granting myself all steam achievements.

Closing because related to the Steam overlay, not to this project.

**Comment by chromKa** [comment]
I haven't used the "get all achievements" feature once! So - it's not associated
