### ISSUE TITLE
Fix to "launching the game node was not found"

### ISSUE THREAD

**Issue by NiceTrick77** [pierre-josselin/payday-2-ultimate-trainer-6#24]
Like in title i fixed this issue with few steps 👍 
So : 
Solution 1 Make sure you have node installed and pc restrarted 
Solution 2 if you have still "node was not found" when when launching the game search "this PC" and go to right click and go to Properties find Advanced system settings it will open Advanced tab now go to Enviromnent Variables and set new variables for User and System Press new on find where node program is located choose node.exe (give Viariable name node) and last but most important RESTART PC

**Comment by pierre-josselin** [comment]
Thank you for your feedback!

**Comment by pierre-josselin** [comment]
6.2.0 has been released with a troubleshooting section and a debugging tool for people having problems with the installation.
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6#troubleshooting
