### ISSUE TITLE
Invisible player

### ISSUE THREAD

**Issue by chromKa** [pierre-josselin/payday-2-ultimate-trainer-6#28]
Not sure, but invisible not works? After choose this function in mission - guard noticed me

**Comment by chromKa** [comment]
In 6.1.0 its OK, works. After update to 6.2.0 - problems?!

**Comment by pierre-josselin** [comment]
I could not reproduce the problem, seems to work fine.

Note that this feature makes you invisible but guards and civilians still hear the sounds you make.

**Comment by chromKa** [comment]
I checked again, it's working fine now. However, once the switch of the invisible player did not work. Perhaps this is a rare mistake

**Comment by pierre-josselin** [comment]
Ok, feel free to re-open if it happens again
