### ISSUE TITLE
Is there are DLC unlocker?

### ISSUE THREAD

**Issue by GEkXD3** [pierre-josselin/payday-2-ultimate-trainer-6#35]
Hello! Is in this version of UT there are DLC unlocker?
UPD: If are, there is it

**Comment by pierre-josselin** [comment]
Hi, there is not DLC unlocker anymore in ultimate trainer and it will not come back.

You can find a standalone DLC unlocker here: https://www.unknowncheats.me/forum/payday-2-a/593567-dlc-unlocker.html
