### ISSUE TITLE
The build features don't work and cause a game crash.

### ISSUE THREAD

**Issue by MMytry** [pierre-josselin/payday-2-ultimate-trainer-6#36]
Hey!

I have issues with the building features. I can select a unit but when I attempt to delete it nothing happens and if I try to spawn it, the selected unit spawns but then the game crashes. 

I tried it with filled body bags and the presents you make in Santa's Workshop heist.

My latest crash log, at least I think this is it:

Application has crashed: C++ exception
mods/Hotline Miami Hud/lua/InteractionPanel.lua:20: attempt to index a nil value

SCRIPT STACK

_add_string_macros() @mods/base/req/core/Hooks.lua:272
selected() lib/units/interactions/interactionext.lua:232
_update_targeted() lib/managers/objectinteractionmanager.lua:464
update() lib/managers/objectinteractionmanager.lua:71
original() lib/setups/gamesetup.lua:807
update() @mods/base/req/core/Hooks.lua:264
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:559

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.142.223
	CPU : AMD Ryzen 5 2600X Six-Core Processor (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2060 / nvldumd.dll[31.0.15.3623]
	Language : english
	Memory :     16309MB 804KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : SteelSeries ApS (SteelSeries Sonar - Gaming (SteelSeries Sonar Virtual Audio Device))

**Comment by pierre-josselin** [comment]
Hi, thank you for your feedback.

Given your crashlog, this seems to be a conflict with your mod "Hotline Miami Hud", not a bug inside UT.

I invite you to try it without this mod.

Could you share with me the following file, I may check if it's fixable:

_mods/Hotline Miami Hud/lua/InteractionPanel.lua:20_

Also, please note you can only delete units you spawned.

**Comment by MMytry** [comment]
Okay, I'll try doing it without the Hotline Miami Hud mod next time. Thanks for telling me that I can delete only spawned units as well.

The file you requested:

if RequiredScript == "lib/managers/hud/hudinteraction" then
    Hooks:PostHook(HUDInteraction, "init", "HMH_HUDInteraction_init", function(self, ...)
	    if HMH:GetOption("interact") then
			self._hud_panel:child(self._child_name_text):set_color(HMH:GetColor("Interaction"))
			self._hud_panel:child(self._child_name_text):set_alpha(HMH:GetOption("InteractAlpha"))
	    end
    end)
    
	Hooks:PreHook(HUDInteraction, "_animate_interaction_complete", "HMH_HUDInteraction_animate_interaction_complete", function(self, bitmap, circle)
		if HMH:GetOption("interact_texture") > 1 then
			circle:set_visible(false)
		end
	end)

elseif RequiredScript == "lib/units/interactions/interactionext" then
	Hooks:PostHook(BaseInteractionExt, "_add_string_macros", "HMH_BaseInteractionExt_add_string_macros", function (self, macros, ...)
	    macros.INTERACT = self:_btn_interact() or managers.localization:get_default_macro("BTN_INTERACT") --Ascii ID for RB
	    if self._unit:carry_data() then
		    local carry_id = self._unit:carry_data():carry_id()
			macros.BAG = managers.localization:text(tweak_data.carry[carry_id]) and managers.localization:text(tweak_data.carry[carry_id].name_id)
	    end
    end)

	Hooks:PostHook(BaseInteractionExt, "interact_start", "HMH_BaseInteractionExt_interact_start", function (self, player, data, ...)
		local t = Application:time()
		if HMH:GetOption("stealth_c4") and managers.groupai:state():whisper_mode() and self._tweak_data.required_deployable and self._tweak_data.required_deployable == "trip_mine" and (t - (self._last_shaped_charge_t or 0) >= 0.25) then
			self._last_shaped_charge_t = t
			return false
		end
	end)
end

**Comment by pierre-josselin** [comment]
Thank you! I will give a look at this
