### ISSUE TITLE
Polish translation 

### ISSUE THREAD

**Issue by POLSKAGUROA** [pierre-josselin/payday-2-ultimate-trainer-6#42]
[main.txt](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/files/12386219/main.txt)
[dialogs.txt](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/files/12386221/dialogs.txt)
B)

**Comment by pierre-josselin** [comment]
Thank you!
