### ISSUE TITLE
Always Installing http-server...

### ISSUE THREAD

**Issue by GOLDASHOLE** [pierre-josselin/payday-2-ultimate-trainer-6#46]
wait 1 hour...
![screenshot20230821](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/142753214/49d453db-6914-485f-8edc-5521ade66d48)
And If using administrator startup, it will pop up directly
![screenshot20230821 (1)](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/142753214/742b8055-40f9-44b3-a542-f8e91a505b55)

**Comment by pierre-josselin** [comment]
Hello, are you using a public or corporate network? If so, I invite you to try again with a private network, or perhaps with a connection sharing of your telephone.

**Comment by GOLDASHOLE** [comment]
> 您好，您使用的是公共网络还是公司网络？如果是这样，我邀请您再试一次专用网络，或者使用电话的连接共享。

What should I do if I use my home network

**Comment by pierre-josselin** [comment]
I don't have a solution for your issue.

But you can try this already installed dev project:

https://drive.google.com/file/d/1cxAmzM1762kUyltZXBOG4Rwza17S49BI/view?usp=sharing

Remove _payday-2-ultimate-trainer-6-main_ and don't run the install script.

**Comment by GOLDASHOLE** [comment]
This works! thanks!

**Comment by pierre-josselin** [comment]
Nice. Please ignore the update available message

**Comment by pierre-josselin** [comment]
@GOLDASHOLE

[Version 6.3.0](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6) is released and should fix your issue, I invite you to try the installation again.

If the problem persists, you can get it from the following repository: [Ultimate Trainer 6 (already installed)](https://drive.google.com/drive/folders/1ii6VwSu2ezoerXJ5Ql59apOgWLU-EIR6?usp=sharing).
