### ISSUE TITLE
When I click ultimate trainer it pulls up a window and says Error Code: -102, unable to connect to server, server may be offline or you may not be connected to the internet. I am connect to the internet and no issues with my connection.

### ISSUE THREAD

**Issue by wally3916** [pierre-josselin/payday-2-ultimate-trainer-6#48]
When I click ultimate trainer it pulls up a window and says Error Code: -102, unable to connect to server, server may be offline or you may not be connected to the internet. I am connect to the internet and no issues with my connection.

**Comment by wally3916** [comment]
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/142838019/2744c6b3-8fd4-44fa-abc7-8cf22cb042de)

**Comment by pierre-josselin** [comment]
- **The application page shows an error (e.g. "unable to connect to server")**

    - Close the game and any open console
    - Create an empty `test.txt` file (lowercase) inside of `payday-2-ultimate-trainer-6-main`
    - Run the game (it will probably get stuck on a black screen)
    - A console will open in the background after a while, use *ALT* + *TAB* to access it

    This will test the different parts of the mod. Once the test is complete, copy the entire contents of the console and share it with us, by creating a [GitHub issue](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/issues), by commenting this [YouTube video](https://www.youtube.com/watch?v=8BbnMmW9Hmg) or by replying the [UnknownCheats thread](https://www.unknowncheats.me/forum/payday-2-a/588542-payday-2-ultimate-trainer-6-a.html).

**Comment by wally3916** [comment]
okie dokie

**Comment by wally3916** [comment]
PAYDAY 2 - Ultimate Trainer 6

--- INSTALLATION ---

Creating environment file... OK
Creating config file... OK
Installing http-server... OK
Installing application...

**Comment by wally3916** [comment]
PAYDAY 2 - Ultimate Trainer 6

--- INSTALLATION ---

Creating environment file... OK
Creating config file... OK
Installing http-server... OK
Installing application... OK
Building application... OK
Installing server... OK
Creating install status file... OK

Successfully installed!

**Comment by wally3916** [comment]
Pierre Thanks you so much it works, perfectly thanks, have a great day!
