### ISSUE TITLE
Cannot connect to the app on my phone

### ISSUE THREAD

**Issue by budlighters** [pierre-josselin/payday-2-ultimate-trainer-6#5]
Everything seems to be working; the console says both the application and server are running. However, when I try to open the app on my phone, it refuses to connect. Strangely, it works fine when I open it on my computer.

Both my phone and computer are on the same network.

**Comment by pierre-josselin** [comment]
Hi, are you sure you are using the correct IP address and port?

Also check that your computer is not running a particular firewall (other than windows firewall), and that your router is not blocking access to your computer. Also, it will probably not work with a public or enterprise/school network.

**Comment by pierre-josselin** [comment]
Please note especially that the IP to access the application from your computer **is different** from that to access it from another device.

**Comment by budlighters** [comment]
Hi, I am using the IP and port provided by the command prompt. I am not using any firewall other than the one that Windows gives you by default. I don't believe my router is blocking access to my computer, but I am unsure how to check this. I am using my home network.

Also, could you please clarify your second comment? I don't fully understand. How do I access it from another device?
Sorry for being a bother, this is not something I really understand.

**Comment by pierre-josselin** [comment]
In 6.0.0-beta, you had to click on the "get-remote-url" file to get the app URL for other devices.  Since version 6.1.0 (released yesterday), you get it directly in the console which opens when launching the game.

**Comment by pierre-josselin** [comment]
I suggest you to refer to this section of the documentation: https://github.com/pierre-josselin/payday-2-ultimate-trainer-6#access-the-app-from-another-device-laptop-phone-tablet

**Comment by budlighters** [comment]
Hi, I understand now. I've got the application working properly now. Thanks for your help.
