### ISSUE TITLE
Unable to close the console

### ISSUE THREAD

**Issue by chromKa** [pierre-josselin/payday-2-ultimate-trainer-6#50]
![Снимок экрана 2023-08-22 180957](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/19959081/d66c7df5-4731-456c-9755-fd9adac43187)

And strange log...

**Comment by pierre-josselin** [comment]
You enabled the BLT developer console.
To close this console, focuse the window and press ALT+F4.

The logs are produced by the BLT built-in dohttpreq() function, 
Unfortunately they cannot be disabled, it is a choice of the BLT developers.

These logs represent the communication between the game and the Ultimate Trainer server.

**Comment by pierre-josselin** [comment]
Closed, as no reply. Feel free to reopen if you still need help.
