### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Fricknelson** [pierre-josselin/payday-2-ultimate-trainer-6#51]
Everything was going well. The button was showing up, the console and the site were working, after that I tried unlocking all masks and materials and when I checked my inventory nothing was there, I tried restarting the game, my computer but nothing seems to work. 

I am playing on Epic games I dont know if this helps in any form

**Comment by Fricknelson** [comment]
Now its working. I dont know what I did

**Comment by pierre-josselin** [comment]
Nice, feel free to open a new issue if needed
