### ISSUE TITLE
Failure to run the server

### ISSUE THREAD

**Issue by kakadou** [pierre-josselin/payday-2-ultimate-trainer-6#55]
Successfully installed,but i opened game A console will open and close
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/64948735/a71d73e1-c6a4-4429-b868-a6b21bad7fa8)

**Comment by pierre-josselin** [comment]
Hi,

The error message is strange and not informative at all.

Please run a test:

- Close the game and any open console
- Create an empty `test.txt` file (lowercase) inside of `payday-2-ultimate-trainer-6-main`
- Run the game (it will probably get stuck on a black screen)
- A console will open in the background after a while, use *ALT* + *TAB* to access it
- Once the test finished, paste here the content of the console

If the test does not give more information, I suggest you to follow this temporary fix:

https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/issues/46#issuecomment-1685881344

**Comment by kakadou** [comment]
The console is as follows 
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/64948735/147349e9-0a94-45ea-bec6-f83cc8d17632)

and it worked fine when I used the temporary fix

**Comment by pierre-josselin** [comment]
Nice, so the next version will fix your issue. I will inform you here when it's released, please ignore the update available message.

**Comment by pierre-josselin** [comment]
@kakadou 

[Version 6.3.0](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6) is released and should fix your issue, I invite you to try the installation again.

If the problem persists, you can get it from the following repository: [Ultimate Trainer 6 (already installed)](https://drive.google.com/drive/folders/1ii6VwSu2ezoerXJ5Ql59apOgWLU-EIR6?usp=sharing).
