### ISSUE TITLE
trainer does not appear on main menu as stated

### ISSUE THREAD

**Issue by colin094** [pierre-josselin/payday-2-ultimate-trainer-6#56]
the mod appears in the blt updater, but has no apparent menu as stated nor is there any settings for the mod. I have confirmed that the install folder is in the mod folder, that the install was successful, and that blt and nodejs were installed correctly(other mods work fine)

**Comment by pierre-josselin** [comment]
Hi,

From what you describe, the mod seems to be correctly installed.

Please check if there is not the "Ultimate Trainer" button (first button of the main menu, above crime.net).

If it is missing, I see two possible reasons:

- For some reason, setting "Hide Ultimate Trainer button from menu" is enabled
- Another of your mods is conflicting with Ultimate Trainer

Anyway, you should can access the application by accessing http://127.0.0.1:1140 in Steam overlay.

**Comment by pierre-josselin** [comment]
Closed, as no reply. Please feel free to reopen if you still need help.
