### ISSUE TITLE
Ultimate trainer key config

### ISSUE THREAD

**Issue by AzazelHD** [pierre-josselin/payday-2-ultimate-trainer-6#57]
Hello. Im currently using trainer v5, but i cant open issues there so i do it here.

I played payday 2 long time ago, and i remember binding different keys for differents menus. Is that possible with v4 or v5? Or everything changed and menus now are accessed by F1 key and choosing the desired one?

**Comment by pierre-josselin** [comment]
Hi, I just checked and Version 4 allowed to binds keys to open different menus, not version 5 because new menu system.

However I strongly recommend you to upgrade to version 6. Older versions are obsolete and some are broken.

**Comment by AzazelHD** [comment]
Oh. Okey. Thanks for the advice.
Can I bind game menu, for example, to a certain key on v6? Or it has same menu as v5?

**Comment by pierre-josselin** [comment]
Hi, v6 menu is totally different, it's a web app accessible via Steam browser or from phone/tablet.

In this version you can directly create keybinds for any feature of the mod.
