### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by XRAZERGAMERX** [pierre-josselin/payday-2-ultimate-trainer-6#60]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
            _apply_cosmetics()  lib/units/armorskinext.lua:148                      
                                lib/units/armorskinext.lua:50                       

-------------------------------

System information:
	Application version : 1.142.225
	CPU : AMD Ryzen 7 4800H with Radeon Graphics (8 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3050 Laptop GPU / nvldumd.dll[31.0.15.3699]
	Language : german
	Memory :     15791MB 112KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Kopfhörer (Realtek(R) Audio))

**Comment by pierre-josselin** [comment]
Thanks for sharing. When does this crash happens ?

**Comment by XRAZERGAMERX** [comment]
its happends randomly when i join a game or when im middle of an game
