### ISSUE TITLE
Ultimate Trainer 5

### ISSUE THREAD

**Issue by AzazelHD** [pierre-josselin/payday-2-ultimate-trainer-6#61]
Sorry for opening an issue about ultimate trainer 5 here, i cant on its repo.

How do i unlock talents? Is that possible?

Screenshot is in spanish, sorry for that

https://prnt.sc/wvnUTCvbJeO9

**Comment by pierre-josselin** [comment]
Hi, It's possible to give yourself perk points, but not to unlock locked perks. About DLC locked perks, you may try to enable DLC unlocker but not sure it will work and will kick when you join other games.
