### ISSUE TITLE
Nodejs server

### ISSUE THREAD

**Issue by AzazelHD** [pierre-josselin/payday-2-ultimate-trainer-6#63]
Hi, when i run payday 2 through steam, a windows console opens saying to close this window before restarting the game. What does it mean? I have to leave it open while playing, right?

And lastly, where is the "server" installed?

**Comment by pierre-josselin** [comment]
Hi,
Yes you have to leave the console open while playing. You can close it after you close your game.
Server is located in _payday-2-ultimate-trainer-6-server_ folder.
