### ISSUE TITLE
Error Code: -102

### ISSUE THREAD

**Issue by polmk** [pierre-josselin/payday-2-ultimate-trainer-6#69]
![Screenshot 2023-09-13 120312](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/144933719/423faf11-a365-40c7-ac84-d5537c82e015)

PAYDAY 2 - Ultimate Trainer 6

--- TEST ---

You must close this window before using the mod!

Checking Node.js version... OK
Checking installation status... OK
Testing application web server... OK
Testing server... OK

All tests passed!
You can now close this window.

**Comment by pierre-josselin** [comment]
Hi, I see you closed your issue, is this fixed ?

**Comment by polmk** [comment]
whoops didn’t mean to close it 

but no i wasn’t able to fix it

**Comment by pierre-josselin** [comment]
[Version 6.3.0](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6) is released today and may fix your issue, I invite you to try the installation again.

If the problem persists, you can get it from the following repository: [Ultimate Trainer 6 (already installed)](https://drive.google.com/drive/folders/1ii6VwSu2ezoerXJ5Ql59apOgWLU-EIR6?usp=sharing).

**Comment by Sonicx161** [comment]
I'm also experiencing the same issue and I tried both files from above. I notice the game launches, the terminal window (cmd) opens and then closes. Which shouldn't be the case of course. That cmd window is supposed to have the server running (at least based on the instillation video)

**Comment by polmk** [comment]
> [Version 6.3.0](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6) is released today and may fix your issue, I invite you to try the installation again.
> 
> If the problem persists, you can get it from the following repository: [Ultimate Trainer 6 (already installed)](https://drive.google.com/drive/folders/1ii6VwSu2ezoerXJ5Ql59apOgWLU-EIR6?usp=sharing).

nope it didn't work, i tried to install from and github and google drive one. Kept getting the same error

**Comment by pierre-josselin** [comment]
@Sonicx161 can you try to [run a test](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6#user-content-troubleshooting-server-not-running)?
Maybe we will get more information

**Comment by Sonicx161** [comment]
Hey @pierre-josselin I forgot to mention I also ran the test and got the same results as the OP

**Comment by pierre-josselin** [comment]
Unfortunately since we don't have more information, I don't have a solution to the problem.

However if any of you are ok for a remote access session with [Teamviewer](https://www.teamviewer.com/fr/) add me on Discord: fiddlesucks. I might be able to get more information myself.

**Comment by bigjimmy4395** [comment]
Im facing the same issue, keep getting error code -102. Im not sure what to do. The game does have me close a window when ever I run it. Im not sure if that has anything to do with it though.

**Comment by pierre-josselin** [comment]
@bigjimmy4395 Did you tried to run also [a test](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6#user-content-troubleshooting-server-not-running)?

**Comment by pierre-josselin** [comment]
I just released 6.3.1 to fix a bug. Not sure it's the same bug as you encounter here but you may try.

**Comment by bigjimmy4395** [comment]
I tried to a test but no window will pop up, I waited for quite a while and nothing happened.

**Comment by SimonCarabajal** [comment]
![Ultimate trainer 6](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/135768121/b47bbc09-acba-4e36-81e4-2c2650924b72)
Hi i got the same problem the error code -102 and this error in the photo

**Comment by pierre-josselin** [comment]
Hi @SimonCarabajal 

Please follow the troubleshooting section [A message like "Windows cannot find node" appears when starting the game](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6#user-content-troubleshooting-node-not-found).

**Comment by pierre-josselin** [comment]
Please note that Steam browser error 102 simply means that it was unable to connect to the server, and is not an Ultimate Trainer error code.

**Comment by phosoupg** [comment]
i got the same problem

**Comment by phosoupg** [comment]
what is the website to do that stuff

**Comment by pierre-josselin** [comment]
Hi, for the most determined people I suggest the following test:

- Close the game and any console already open
- Navigate inside the `payday-2-ultimate-trainer-6-main` directory
- From this directory, press ALT + F
- Click on "Open PowerShell"
- Paste the command `node .\payday-2-ultimate-trainer-6-server\src\index.js` and press ENTER
- While keeping the first console open, open another one
- Paste the command `node node_modules\http-server\bin\http-server --port 1140 --proxy "http://127.0.0.1:1140?" payday-2-ultimate-trainer-6-app\dist` and press ENTER
- Run the game, try to access application and see if there any message in the PowerShell consoles

**Comment by airblizzard** [comment]
I'm not the OP but I'm having the same issue. This is what I got.

<img width="1133" alt="image" src="https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/97088630/c7cbfcf3-0d70-4494-9a56-f7268602acbc">

**Comment by pierre-josselin** [comment]
> I'm not the OP but I'm having the same issue. This is what I got.
> 
> <img width="1133" alt="image" src="https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/97088630/c7cbfcf3-0d70-4494-9a56-f7268602acbc">
> 

Hi @airblizzard 
Given the logs you was able to open http://127.0.0.1:1140 right?

**Comment by airblizzard** [comment]
Hi Pierre,

I wasn't. I got the Error Code: -102 
Unable to connect to server.

**Comment by pierre-josselin** [comment]
@airblizzard really strange

**Comment by pierre-josselin** [comment]
I think the only way for me to find out the problem is to check it by myself with teamviewer. If someone is interested, Discord me: fiddlesucks

**Comment by pierre-josselin** [comment]
With the help of @airblizzard, we was able to identify the issue. The server does not run automatically for some (Windows 11?) users.

A simple and good fix we found is to create an empty **text file** named `developer` inside the `mods`  folder.
