### ISSUE TITLE
Hook and Persist

### ISSUE THREAD

**Issue by chromKa** [pierre-josselin/payday-2-ultimate-trainer-6#74]
Whats hooks and persist in Addons menu?

**Comment by pierre-josselin** [comment]
It's the same as keybinds, hooks and persist scripts from [BLT documentation](https://payday-2-blt-docs.readthedocs.io/en/latest/mods/definition/), but with GUI and support changes without restart the game.

Some features needs to be hooked or persisted to work properly ([some examples](https://www.unknowncheats.me/forum/payday-2-a/322033-lua-scripts-snippets-collection-create-requests-updated-04-10-2020-a.html)).
