### ISSUE TITLE
japanese translation

### ISSUE THREAD

**Issue by nattsuiy** [pierre-josselin/payday-2-ultimate-trainer-6#8]
i translated into japanese

[main.txt](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/files/12210934/main.txt)
[dialogs.txt](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/files/12210935/dialogs.txt)
[en.txt](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/files/12210936/en.txt)

**Comment by pierre-josselin** [comment]
Much appreciated, thank you

Will be included in next release
