### ISSUE TITLE
Any plan for Payday 3?

### ISSUE THREAD

**Issue by TehChozinOne** [pierre-josselin/payday-2-ultimate-trainer-6#80]
Love ur trainer. Have you looked into PD3 much or any plan to do something similar?

**Comment by chromKa** [comment]
Yea, we are waiting

**Comment by pierre-josselin** [comment]
Hi! It's possible but not planned for the moment, I have many projects and I must prioritize monetized projects

**Comment by TehChozinOne** [comment]
> Hi! It's possible but not planned for the moment, I have many projects and I must prioritize monetized projects

oh? I have a quick look at your repos and I dont see any monetized projects. Which repos were you referring to?

**Comment by pierre-josselin** [comment]
Indeed that's private repos about my job

**Comment by chromKa** [comment]
> Indeed that's private repos about my job

in any case, we are looking forward to the implementation from you, Pierre, for Payday 3

**Comment by TehChozinOne** [comment]
> Indeed that's private repos about my job

ah okay. fair enuff

**Comment by pierre-josselin** [comment]
Yeah I consider to do something similar for PD3, just not sure when 😃
