### ISSUE TITLE
Game won't launch after enabling Skill Point hack

### ISSUE THREAD

**Issue by 8l172** [pierre-josselin/payday-2-ultimate-trainer-6#81]
Game starts then immediantly closes itself after I have enabled the skill point hack, only fix was removing the files from my mods folder but re-adding them back had the same issue

**Comment by 8l172** [comment]
Updating to say I managed to get it launching again but now I have 0 skill points (had 5 previously) and trying to add more does not work, says "Sent" but I do not gain any more points

**Comment by pierre-josselin** [comment]
Hi, could you please send your crash file? You can get it from bug icon at top-right of the app
