### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Silnetwolf4** [pierre-josselin/payday-2-ultimate-trainer-6#82]
payday 2 ultimate trainer 6 does not work at all. i am using ultimate trainer 5 and its working just fine. fix ultimate trainer 6 asap. or bring back the ablity to download ulitmate trainer 5 again.

**Comment by pierre-josselin** [comment]
It works without any problem for the vast majority of users, if you do not provide additional details I cannot help you.

**Comment by Silnetwolf4** [comment]
> It works without any problem for the vast majority of users, if you do not provide additional details I cannot help you.

i have no problems with trainer 5. but when i try to put trainer 6 into my mods folder and lunch the game it does not show up at all like number 5 does for me.

**Comment by pierre-josselin** [comment]
Did you follow the installation procedure which is different from version 5:

https://github.com/pierre-josselin/payday-2-ultimate-trainer-6#installation

**Comment by Silnetwolf4** [comment]
> Did you follow the installation procedure which is different from version 5:
> 
> https://github.com/pierre-josselin/payday-2-ultimate-trainer-6#installation
 Ya i did and i even  have WSOCK32.dll installed

**Comment by pierre-josselin** [comment]
So when you start the game a console opens?

**Comment by Silnetwolf4** [comment]
> So when you start the game a console opens?

Sometimes the console crashes when i try to run it. and half the time does not like to work. takes me 3 to 5 trys to get the console to work like the video. when i had t 5 i had no problems. Not like this. would been nice if it was made the same way.

**Comment by pierre-josselin** [comment]
I understand your wish but I do not want to do something like version 5, but something bigger, which requires a more complex installation unfortunately.

I invite you to run a test to see what is not working:

> - Close the game and any open console
> - Create an empty `test.txt` file (lowercase) inside of `payday-2-ultimate-trainer-6-main`
> - Run the game (it will probably get stuck on a black screen)
> - A console will open in the background after a while, use *ALT* + *TAB* to access it
> 
> This will test the different parts of the mod. Once the test is complete, copy the entire contents of the console and share it with us

**Comment by Silnetwolf4** [comment]
Now its working fine. I guess just got to say its gonna get tested for stuff to work lol
