### ISSUE TITLE
Game crashing at the start of the heist or loading screen

### ISSUE THREAD

**Issue by G-ReM** [pierre-josselin/payday-2-ultimate-trainer-6#83]
Installed everything properly. Ultimate cheat 6 was working perfectly for like 1 hour. Then the game crashed once and since then I cannot start a heist. I can start the game, go through the menu, chose a heist, but if I try to start the heist the game crashes. Tried to verify game files (I'm on steam), restarted my computer, nothing fixes the issue.

**Comment by pierre-josselin** [comment]
Hi, please share you crash file, you can get it from the bug icon at top-right of the app, or directly here:

%LOCALAPPDATA%\PAYDAY 2\crash.txt

**Comment by G-ReM** [comment]
Hey so I noticed it was happening when I tried to buy a contract from the contract brocker (offline/online). But now I managed to join an online mission (white house) finish it after that  I managed to start an offline mission from the contract brocker... Here the crash file
 
[crash.txt](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/files/12701271/crash.txt)

**Comment by pierre-josselin** [comment]
Hi have you checked loading of some vehicles in driving menu ? If yes, please uncheck them all and try again.

**Comment by G-ReM** [comment]
It is not impossible that I clicked something in the driving menu. After the first couple of crashes I tried to deactivated every cheat, I restarted steam, restarted computer, I reinstalled the ultimate trainer, but the game was still crashing when I chose to start a heist using the contract broker. The crash occured every time just after loading the heist, on the screen where you have to tick the box on the bottom right to start. 

At some point I decided to try and join someones elses heist online. And I joined without a problem and helped that person do the White House heist. After that I was able again to normally start heists using the contract broker without the game crashing.

**Comment by pierre-josselin** [comment]
Glad to hear your issue is resolved. The crashlog and issue you describe looks very similar to a Driving menu crash. I invite you not to check the loading of more than one vehicle at a once next time, to avoid reproducing this issue. Feel free to contact us again if you have any further problems.
