### ISSUE TITLE
install file error

### ISSUE THREAD

**Issue by Crul0** [pierre-josselin/payday-2-ultimate-trainer-6#85]
I have Node 18 and everything in the right spot but I'm still getting this error.
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/88393172/e20a3880-450b-480a-a368-504999e665b2)
Please help

**Comment by pierre-josselin** [comment]
Hi, thank you for your feedback. I will investigate and come back to you tomorrow.

**Comment by RedbrickCobra66** [comment]
okay ty

**Comment by pierre-josselin** [comment]
As temporary fix, I invite you to try the already installed version:

https://drive.google.com/drive/folders/1ii6VwSu2ezoerXJ5Ql59apOgWLU-EIR6

Dont run the install script with this version

**Comment by RedbrickCobra66** [comment]
okay tyyy
