### ISSUE TITLE
Not able to change skill points

### ISSUE THREAD

**Issue by HarryBaboon** [pierre-josselin/payday-2-ultimate-trainer-6#9]
I'm unable to add/remove skill points through the trainer, no matter what value or where in Payday I activate it. Everything else is working fine.

**Comment by pierre-josselin** [comment]
Hi, just tested it (6.1.0) and I confirm it's working:

![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/70814177/c7e2d97b-58bc-4c77-8a48-ec3659c2020b)

![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/70814177/2ae9b2e2-113f-4c3f-b9c1-09f278793437)

You need to close and re-open your game, did you?

**Comment by HarryBaboon** [comment]
Oh I was using it wrong, got it. You have to restart the game after selecting the amount of skill points you want in order for it to change. I thought you just had to restart after enabling it in order for it to work in game after that. My bad.

**Comment by pierre-josselin** [comment]
That's it, no problem!
