### ISSUE TITLE
"System don't find node file"

### ISSUE THREAD

**Issue by Honn3ts** [pierre-josselin/payday-2-ultimate-trainer-6#91]
When i launch the game, it says me "System don't find node file" after, in game the game works normally but when i click the utlime trainer button it's say :

Error code-102
Unable to connect to server. The server may be offline, or your computer may not be connected to the Internet.

**Comment by pierre-josselin** [comment]
Hi, please follow the section "Troubleshooting - Windows cannot find node":

https://github.com/pierre-josselin/payday-2-ultimate-trainer-6#troubleshooting-node-not-found
