### ISSUE TITLE
Onglet Tricheur

### ISSUE THREAD

**Issue by bySz972** [pierre-josselin/payday-2-ultimate-trainer-6#97]
Bonjour je voulais savoir, en utilisant ton logiciel, on aura longlet tricheur sur la tete ?

**Comment by pierre-josselin** [comment]
Bonjour, l'étiquette "TRICHEUR" apparaît dès que tu utilise des fonctionnalités détectées par l'anti cheat du jeu (icone jaune dans l'appli) et disparait dès que la partie se termine.
